### ISSUE TITLE
Unread mail count for selected folder not working

### ISSUE THREAD

**Issue by joelekstrom** [joelekstrom/fastmate#15]
Seems like Fastmail has changed something so will need to look into that.

As a workaround: Use unread mail count **For all folders** or ** For specific folders** in settings for now

**Comment by posguy99** [comment]
Fastmail changed their DOM to no longer include v-MailBoxSource-badge for the Archive and Sent mailboxes, FYI.

I opened a ticket and got back:

Marc, I heard from our engineers and this is what they
say:

Our DOM structure is not guaranteed to remain stable in
any way and we can't provide support for user scripts.
In this case, we do not include a DOM element for a
badge if the folder will never show a badge, as is the
case with some system folders.

Regards,

Yassar Ali
FastMail Support

So if you're depending on some specific aspect of the DOM, that's why.

**Comment by joelekstrom** [comment]
@posguy99 Thanks for the information! The selected folder unread functionality in Fastmate actually uses the title of the website. I see they removed the parentheses around the number which makes my regex fail, should be an easy fix.

**Comment by joelekstrom** [comment]
Fixed in [v1.4.1](https://github.com/joelekstrom/fastmate/releases/tag/v1.4.1)

**Comment by posguy99** [comment]
It's stopped working again.  Did Fastmail change the format again?

**Comment by posguy99** [comment]
Better still... v1.4.2(1) on my MBP correctly displays the unread count, but v1.4.2(1) on my iMac does not.  Same binary, same OS, same patches.

**Comment by joelekstrom** [comment]
What settings do you have in Fastmate-settings for unread count on your computers?

**Comment by posguy99** [comment]
Here you go.

On the iMac, where it doesn't work...

![Fastmate settings iMac](https://user-images.githubusercontent.com/408644/79051410-f7e59680-7be4-11ea-9bac-938da4572475.jpg)

On the MBP, where it does work:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/408644/79051425-092ea300-7be5-11ea-82d5-590b24ff8e8a.png">

They're the same.

On the iMac, it doesn't matter whether I do Selected Folder, or All Folders, or just Inbox.

And the truly weird thing is... it USED to work.

**Comment by joelekstrom** [comment]
Interesting - thanks for helping investigate. Two more things you can check:

- In OSX system settings -> Notifications -> Are you allowing Fastmate to show badges? (or allowing notifications at all)
- Are you using Fastmail beta on any of the computers, in the Fastmate-settings?

**Comment by posguy99** [comment]
Neither.

--
Marc Wilson
posguy99@gmail.com

**Comment by posguy99** [comment]
Here’s a funny for you... I rebooted the machine for something else, and the dock icon badge is working again.  So some hook somewhere was definitely stuck.

**Comment by joelekstrom** [comment]
🤔 glad it works. Let me know if it happens again, I don’t think I can investigate much further unfortunately

**Comment by posguy99** [comment]
I'll do that.

**Comment by posguy99** [comment]
Just FYI, I replaced 1.4.2 with 1.5.0, and the non-badging of the dock icon is back.  I tried to revert back to 1.4.2, and 1.4.2 won't launch.

**Comment by joelekstrom** [comment]
Thanks for reporting! It seems to work for me - can you show me what your settings are in 1.5.0 for the unread badge? Also can you check your system notification settings again if Fastmate 1.5.0 is allowed to show badges?

**Comment by joelekstrom** [comment]
hey @posguy99, could you test and see if this version solves the problem? 
[Fastmate-1.5.1-beta.zip](https://github.com/joelekstrom/fastmate/files/4529326/Fastmate-1.5.1-beta.zip)

**Comment by posguy99** [comment]
v1.5.1 still says it's from an unidentified developer.

It crashes on launch the same as v1.4.2 does (now).  v1.5.0 doesn't crash.  I rebooted the machine and the badging of the dock icon is working again. It's only a reboot that seems to fix it, I've tried restarting the Dock process and that didn't change anything.

The crash is:

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: bundleProxy != nil'
terminating with uncaught exception of type NSException
abort() called

**Comment by joelekstrom** [comment]
Unidentified developer should be expected. I haven’t signed any of the versions so should have always been the case. Will have to look into those crashes though, that’s very strange 🤔

**Comment by joelekstrom** [comment]
@posguy99 Here's another version that I hope should fix the crash, please give it a try and sorry for all the trouble!

[Fastmate-1.5.1-beta2.zip](https://github.com/joelekstrom/fastmate/files/4529827/Fastmate-1.5.1-beta2.zip)

**Comment by posguy99** [comment]
Nope.  BOOM! again.

Same error.

Process:               Fastmate [19987]
Path:                  /private/var/folders/*/Fastmate.app/Contents/MacOS/Fastmate
Identifier:            io.ekstrom.Fastmate
Version:               1.5.1 (2)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Fastmate [19987]
User ID:               501

Date/Time:             2020-04-25 08:12:43.867 -0700
OS Version:            Mac OS X 10.14.6 (18G4032)
Report Version:        12
Anonymous UUID:        2A76C314-8AFE-BD60-069A-087862B98653

Sleep/Wake UUID:       8DCC1995-96EC-4C02-BBDC-A0EFD3964A66

Time Awake Since Boot: 110000 seconds
Time Since Wake:       3600 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: bundleProxy != nil'
terminating with uncaught exception of type NSException
abort() called


v1.5.0 doesn't crash, but it stopped badging the icon with the unread count again.  It comes back if I reboot the machine (I suppose I should also try logging off and back on), but stops again shortly afterwards.

**Comment by posguy99** [comment]
The complete backtrace is here:

https://drive.google.com/file/d/1yj1ABvF9_tA3qqnN6tawdc4VljvwqA50/view?usp=sharing

**Comment by joelekstrom** [comment]
Thanks for the stack trace! That’s very helpful. It’s related to the fix for notifications (#16), and seems to be a bug in the “new” Notification Center from Apple. I see other apps have run into the same and I’ll try to work around it. I’ll probably post another beta for you soon, and I really appreciate all the help here.

**Comment by joelekstrom** [comment]
@posguy99 Attempt number 3. I moved the notification center registration to happen a bit later. I see other apps get the same crash but haven't seen anyone figure out a solution yet, so just trying random things at this point...

[Fastmate-1.5.1-beta3.zip](https://github.com/joelekstrom/fastmate/files/4534737/Fastmate-1.5.1-beta3.zip)

**Comment by posguy99** [comment]
Ok, I tested this one on my other Mojave machine first, which isn't really as good a test as it could be since it's not the same machine.  I'll test on the original machine tonight.

On this machine (MBP) v1.4.2 still works, while in the iMac it doesn't.

But 1.5.1b3 still crashes.

Backtrace is here:

https://drive.google.com/open?id=1mymVULKPA4zIOmmQBLTkKbzyWvQTBIzI

**Comment by posguy99** [comment]
Ok, 1.5.1b3 crashes on the iMac too, here's the backtrace.  v1.42 still continues to crash here while it works correctly on my other Mojave Mac (the MBP) as well.

https://drive.google.com/open?id=1FcNfjwXJ0mMw0NX1M1H88fuUkJ0FZ3mo

**Comment by joelekstrom** [comment]
Getting tired of `UNNotificationCenter`... here's another try which moves things around quite a bit and tries [the accepted answer here](https://stackoverflow.com/questions/43840090/calling-unusernotificationcenter-current-getpendingnotificationrequests-crashe) which is the only thing I've found of someone getting somewhere with this crash 🤦‍♂️ 

[Fastmate-1.5.1-beta4.zip](https://github.com/joelekstrom/fastmate/files/4548332/Fastmate-1.5.1-beta4.zip)

**Comment by joelekstrom** [comment]
Just FYI @posguy99 i set up a virtual machine running the latest Mojave and I can’t reproduce the crash 🤔 so that’s strange. I wonder if it’s related to some software you have on your machines. Feel free to try the last beta I posted above!

**Comment by posguy99** [comment]
I figured it out. It’s App Translocation doing it. If you put the binary in the Applications folder, the crash doesn’t happen.

--
Marc Wilson
posguy99@gmail.com

**Comment by posguy99** [comment]
Namely v1.50 doesn’t crash any more.

--
Marc Wilson
posguy99@gmail.com

**Comment by posguy99** [comment]
However, the unread count still does not work on *this* machine unless I restart, then it dies again later.  Open to ideas as to why.  My Fluid SSB can always badge the icon. :(

**Comment by joelekstrom** [comment]
Oh, nice find! Thanks for the info. Does the indicator not work in the last beta I posted?

**Comment by posguy99** [comment]
No, 1.5.1b4 does not show the unread bubble on the dock icon.  Just tried it.

On the left is Fastmate, on the right is my Fluid SSB.

![2020-05-17-19-54-43 image](https://user-images.githubusercontent.com/408644/82170171-87cbcf80-9878-11ea-9d4e-fe949f1107c4.jpg)

**Comment by posguy99** [comment]
I just got my shiny new MBP 2020... and the indicator does not work there on Catalina, either, with v1.50 or v1.51b4.  And restarting the machine doesn't make it work.  Sorry for the bad news.

**Comment by posguy99** [comment]
I also noticed that:

My Fluid SSB no longer appears in System Preferences>Notifications *at all* on Catalina, so I think my using Fluid is finally done, for this purpose at least.  There was a StackExchange posting from someone else describing the same behavior on Catalina, so absent Fluid's author publishing something...

Fastmate *does* appear in System Preferences>Notifications in Catalina, so that's all to the good, but *missing* is the "Badge Dock Icon" switch, so I assume Fastmate is not promoting some property that it needs in order to do that, for the selector to appear, and for it to actually badge the Dock icon..  None of the progression between 1.50 and 1.51b4 have the switch.

**Comment by joelekstrom** [comment]
That's useful information! Thank you, I'll look into that.

**Comment by joelekstrom** [comment]
@posguy99 I found my mistake regarding the badge, I'm pretty sure this version should fix it 😅 please let me know!

[Fastmate-1.5.1-beta5.zip](https://github.com/joelekstrom/fastmate/files/4676011/Fastmate-1.5.1-beta5.zip)

**Comment by posguy99** [comment]
Yup.  Works on Catalina now, and the correct selections show up in System Preferences >> Notifications.

But it STILL does not work on my Mojave iMac unless I restart it, and then it stops working later.  I'm perfectly willing to believe there's something on that machine that somehow blocks Fastmate from being able to badge the app, is there any logging so we could see an error?  Does Fastmate fail the badge, or does it think it succeeded and the OS just doesn't let it happen?

**Comment by joelekstrom** [comment]
Regarding the badge - yes, Fastmate just tells the OS to set the badge, there's no failure callback or anything, so not really anything I can log there.

*However*, we can find out if the bug is on the Fastmate side - if you enable the unread badge on the status bar item:

- If you see the badge in the menu bar but not in the dock:
  - I'm inclined to believe it's something on your set up that breaks it, since the indicators are enabled at the same time from the Fastmate side
- If there's no badge in the menu bar item:
  - Definitely something wrong in Fastmate. Since the issue starts happening after a while, it might be that Mojave pauses javascript execution in the background after some time, but Catalina does not.

**Comment by posguy99** [comment]
Well, it's been two days since my last reboot on Mojave, and the badge has persisted all this time.  Maybe b5 caught whatever it was.

Yeah, through all this the unread indicator in the menu bar would indicate there were unreads.  *Fastmate* is figuring it out just fine, it's the displaying of the badge specifically.

**Comment by joelekstrom** [comment]
Also great info. If you’ve seen it in menu bar, I think I’ve done what I can from the Fastmate side. It may very well be beta 5 that solved it since I had missed to request authorisation for showing badges before that. Gonna release beta 5 for everyone. Thanks for all the help! 🙏

**Comment by joelekstrom** [comment]
Hopefully fixed in [1.5.1](https://github.com/joelekstrom/fastmate/releases/tag/v1.5.1)
